config/routes.rb
Carpoolr::Application.routes.draw do
  resources :riders do
    collection do
      get :waiting
      get :set_destination_spot
      get :sf_waiting
    end
  end

  resources :drivers do
    collection do
      get :waiting
      get :set_destination_spot
      get :sf_waiting
    end
  end
  
  resources :pickup_spots

  root to: 'home#index'
end

app/models/destination_spot.rb
class DestinationSpot < ActiveRecord::Base
  MAX_LAST_SEEN_AT = 5.minutes
  # attr_accessible :name
  has_many :waiting_riders, -> { where(last_seen_at: MAX_LAST_SEEN_AT.ago..(Time.current)) }, :class_name => "Rider"
  has_many :waiting_drivers, -> { where(last_seen_at: MAX_LAST_SEEN_AT.ago..(Time.current)) }, :class_name => "Driver"
  
end

app/models/driver.rb
# == Schema Information
#
# Table name: drivers
#
#  id              :integer         not null, primary key
#  number_of_seats :integer         default(0), not null
#  lat             :decimal(3, 10)
#  lng             :decimal(3, 10)
#  last_seen_at    :datetime
#  created_at      :datetime
#  updated_at      :datetime
#

class Driver < ActiveRecord::Base
  MAX_LAST_SEEN_AT = 5.minutes
  # attr_accessible :number_of_seats, :lat, :lng, :last_seen_at, :pickup_spot, :destination_spot
  belongs_to (:pickup_spot)
  belongs_to (:destination_spot)
  validates_presence_of :pickup_spot

  def self.waiting_condition
    {:last_seen_at => MAX_LAST_SEEN_AT.ago..(Time.current)}
  end

  def seen!
    update_attributes(:last_seen_at => Time.current)
  end
end

app/models/pickup_spot.rb
# == Schema Information
#
# Table name: pickup_spots
#
#  id           :integer         not null, primary key
#  name         :string(255)
#  lat          :decimal(3, 10)
#  lng          :decimal(3, 10)
#  last_seen_at :datetime
#

class PickupSpot < ActiveRecord::Base
  # attr_accessible :name, :lat, :lng

  MAX_LAST_SEEN_AT = 5.minutes
  reverse_geocoded_by :lat, :lng

  has_many :waiting_riders, -> { where(last_seen_at: MAX_LAST_SEEN_AT.ago..(Time.current)) }, :class_name => "Rider"
  has_many :waiting_drivers, -> { where(last_seen_at: MAX_LAST_SEEN_AT.ago..(Time.current)) }, :class_name => "Driver"
  
  def self.san_francisco
    find_by_name("San Francisco") || raise("San Francisco not found! (earthquake?)")
  end

  def self.find_closest(lat, lng)
    self.near([lat, lng], 5).first
  end
end

app/models/rider.rb
# == Schema Information
#
# Table name: riders
#
#  id             :integer         not null, primary key
#  pickup_spot_id :integer
#  last_seen_at   :datetime
#  created_at     :datetime
#  updated_at     :datetime
#

class Rider < ActiveRecord::Base
  MAX_LAST_SEEN_AT = 5.minutes
  # attr_accessible :last_seen_at, :destination_spot, :pickup_spot
  validates_presence_of :pickup_spot_id
  belongs_to(:pickup_spot)
  belongs_to(:destination_spot)

  def self.waiting_condition
    {last_seen_at: MAX_LAST_SEEN_AT.ago..(Time.current)}
  end

  def self.destination_waiting_condition
    {last_seen_at: MAX_LAST_SEEN_AT.ago..(Time.current)}
  end

  def seen!
    update_attributes(last_seen_at: Time.current)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/drivers_controller.rb
class DriversController < ApplicationController
  def new
    if location = cookies[:location]
      lat, lng = location.split('--').map(&:to_f)

      go_to_spot PickupSpot.find_closest(lat, lng)
    end
  end

  def create
    Drivers::Create.call(
      driver: params[:driver],
      session: session
    )

    redirect_to action: :waiting
  end

  def set_destination_spot
  end

  def waiting
    @driver = Driver.find_by_id(session[:driver_id])
    @destination_spot = @driver.destination_spot
    return redirect_to root_path unless @driver
    @driver.seen!
  end

  def destroy
    @driver = Driver.find_by_id(session[:driver_id])
    @driver.destroy if @driver
    redirect_to root_path
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
  
  def find_a_ride
  end

  def find_riders
  end
end

app/controllers/pickup_spots_controller.rb
class PickupSpotsController < ActionController::Base
  def index
    all_status
  end

  def all_status
  end
end

app/controllers/riders_controller.rb
class RidersController < ApplicationController
  def new
    if location = cookies[:location]
      lat, lng = location.split('--').map(&:to_f)

      go_to_spot PickupSpot.find_closest(lat, lng)
    end
  end

  def sf_create(rider)
    @destination_spot = DestinationSpot.find_by_id(rider[:destination_spot_id])
    pickup_spot = PickupSpot.find_by_name("San Francisco")
    @rider = Rider.create!(:pickup_spot => pickup_spot, :destination_spot => @destination_spot)
    session[:rider_id] = @rider.id
    redirect_to :action => :sf_waiting
  end

  def create
    rider = params[:rider]

    if rider[:destination_spot_id]
      sf_create(rider)
    else
      go_to_spot PickupSpot.find_by_id(rider[:pickup_spot_id])
    end
  end
  
  def waiting
    @rider = Rider.find_by_id(session[:rider_id])
    return redirect_to root_path unless @rider
    @rider.seen!
  end

  def sf_waiting
    @rider = Rider.find_by_id(session[:rider_id])
    return redirect_to root_path unless @rider
    @rider.seen!
  end

  def destroy
    @rider = Rider.find_by_id(session[:rider_id])
    @rider.destroy if @rider
    redirect_to root_path
  end

  def set_destination_spot
  end

  private

  def go_to_spot(pickup_spot)
    if pickup_spot.name == "San Francisco"
      redirect_to :action => :set_destination_spot
    else
      @rider = Rider.create!(:pickup_spot => pickup_spot)
      session[:rider_id] = @rider.id
      redirect_to :action => :waiting
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def button_link_to(content, url, options = {})
    link_to(content, url, options.reverse_merge("data-role" => "button", "data-ajax"=>"false" ))
  end
end

app/views/drivers/_navigation.html.erb
<%= button_link_to "Refresh", '', :method => :get %>

<%= button_link_to "Exit/Got my Riders!", @driver,  :method => :delete %>

app/views/drivers/new.html.erb
<p>If you are waiting for riders, just hit your location below to tell them you're waiting</p>
<% PickupSpot.all.each do |spot| %>
  <%= button_link_to spot.name, drivers_url(:driver => {:pickup_spot_id => spot.id}), :method => :post  %>
<% end %>

app/views/drivers/set_destination_spot.html.erb
<%= render 'shared/spot_select', :type => :driver %>

app/views/drivers/sf_waiting.html.erb
<p>It won't be too long before you're cruising along!</p>

<p>Hit refresh to update the stats below and publish that you're still waiting, you will be marked as stale after <%= distance_of_time_in_words Rider::MAX_LAST_SEEN_AT %> of inactivity </p>
<%= render 'shared/spot_stats' %>

<%= render 'navigation' %>

app/views/drivers/waiting.html.erb
<p>You're all set!</p>

<%= render 'shared/waiting_stats', :resource => @driver %>

<p>
  Hit the refresh button at least every <%= distance_of_time_in_words Rider::MAX_LAST_SEEN_AT %> to avoid being marked as stale. You will also see if any riders might be on their way
</p>

<%= render 'navigation' %>

app/views/home/index.html.erb
<p>Finding your location... <span id="status">checking...</span></p>
<script>
  $(function () {
    var s = $('#status');

    function success(position) {
      s.html("found you!");
      setCookie('location', "" + position.coords.latitude + "--" + position.coords.longitude)
    }

    function error(msg) {
      s.html(typeof msg == 'string' ? msg : "failed");
    }

    var timeout = (document.location.href.indexOf('slow_location') >= 0 ? 200 : 0);

    setTimeout(function(){
      if (navigator.geolocation) {
        navigator.geolocation.getCurrentPosition(success, error);
      } else {
        error('not supported');
      }
    }, timeout)
  });

  function setCookie(name,value) {
    document.cookie = name+"="+value+"; path=/";
  }
</script>

<%#= button_link_to "Who's waiting?", pickup_spots_path %>

<br/>
<br/>
<br/>

<%= button_link_to "I need &nbsp; #{image_tag('car_symbol.png')}".html_safe, new_rider_path %>

<br/>
<br/>
<br/>

<%= button_link_to "I need &nbsp; #{image_tag('man_symbol.png')}".html_safe, new_driver_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Carpoolr</title>

    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="http://code.jquery.com/mobile/1.0.1/jquery.mobile-1.0.1.min.css" />
    <script src="http://code.jquery.com/jquery-1.6.4.min.js"></script>
    <script src="http://code.jquery.com/mobile/1.0.1/jquery.mobile-1.0.1.min.js"></script>

    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
  </head>

  <body>

    <div data-role="page">

      <div data-role="header">

        <h1>Find CarpooLRz</h1>

      </div> <!-- /header -->

      <div data-role="content">
        <%= yield %>
      </div> <!-- /content -->

      <%= debug(params) if Rails.env.development? %>

      <div data-role="footer">
        <h4>go green</h4>
      </div> <!-- /footer -->

    </div>
  </body>
</html>

app/views/pickup_spots/index.html.erb
<p>Who's waiting at... </p>
<br />
<% PickupSpot.all.each do |spot| %>
  <%= button_link_to spot.name, pickup_spots_path %>
<% end %>

app/views/riders/_navigation.html.erb
<%= button_link_to "Refresh", '' %>
<%= button_link_to "Exit/Got my Ride!", @rider,  :method => :delete %>

app/views/riders/new.html.erb
<p>Where are you waiting? </p>
<% PickupSpot.all.each do |spot| %>
  <%= button_link_to spot.name, riders_url(:rider => {:pickup_spot_id => spot.id}), :method => :post %>
<% end %>

app/views/riders/set_destination_spot.html.erb
<%= render 'shared/spot_select', :type => :rider %>

app/views/riders/sf_waiting.html.erb
<p>It won't be too long before you're cruising along!</p>

<p>Hit refresh to update the stats below and publish that you're still waiting, you will be marked as stale after <%= distance_of_time_in_words Rider::MAX_LAST_SEEN_AT %> of inactivity </p>
<%= render 'shared/spot_stats' %>

<%= render 'navigation' %>

app/views/riders/waiting.html.erb
<p>You're all set!</p>

<%= render 'shared/waiting_stats', :resource => @rider %>

<p>
  Hit the refresh button at least every <%= distance_of_time_in_words Rider::MAX_LAST_SEEN_AT %> minutes to avoid being marked as stale. You will also see if any drivers might be on their way
</p>

<%= render 'navigation' %>

app/views/shared/_spot_select.html.erb
<p>Where are you going?</P>
<% DestinationSpot.where(["name != ?", "San Francisco"]).each do |spot| %>
  <%= button_link_to spot.name, send("#{type}s_path", type => {:destination_spot_id => spot.id}), :method => :post %>
  </br>
<% end %>

app/views/shared/_spot_stats.html.erb
<table>
  <tr>
    <td>
      Destination
    </td>
    <td />
    <td>
      <%= image_tag('man_symbol.png') %>
    </td>
    <td />
    <td>
      <%= image_tag('car_symbol.png') %>
    </td>
  </tr>
  <% DestinationSpot.where.not(name: 'San Francisco').each do |spot| %>
    <tr>
      <td>
        <%= spot.name %>
      </td>
      <td />
      <td>
        <%= spot.waiting_riders.count %>
      </td>
      <td />
      <td align="center">
        <%= spot.waiting_drivers.count %>
      </td>
    </tr>
  <% end %>
</table>

app/views/shared/_waiting_stats.html.erb
<table>
  <tr>
    <td>
      <%= resource.pickup_spot.name %>
    </td>
    <td />
    <td>
      <%= image_tag('man_symbol.png') %>
    </td>
    <td />
    <td>
      <%= image_tag('car_symbol.png') %>
    </td>
  </tr>
  <tr>
    <td />
    <td />
    <td>
      <%= resource.pickup_spot.waiting_riders.count %>
    </td>
    </td>
    <td />
    <td align="center">
      <%= resource.pickup_spot.waiting_drivers.count %>
    </td>
  </tr>
</table>